repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-yaml
        args: ['--unsafe']
      - id: detect-private-key
  - repo: local
    hooks:
      - id: format
        name: run formatting
        entry: make format
        language: system
        pass_filenames: false
        stages:
          - commit
